name: Bedwars
version: '${project.version}'
main: de.juliuskxyz.bedwars.Bedwars
api-version: 1.20
authors: [ Juliuskxyz, MiSkynet ]
description: Bedwars Plugin
commands:
  setlocation:
    description: Set a position for all Positions
  teleportto:
    description: Teleport to a location
  start:
  stopGame:
