name: TNTFight
version: '${project.version}'
main: de.juliuskxyz.tntfight.TNTFight
api-version: 1.20
authors: [ Juliuskxyz, MiSkynet ]
description: 5v5 TNT Fight Plugin
commands:
  setlocation:
    description: Set a position for all Positions
  teleportto:
    description: Teleport to a location
  start:
  stopGame:
